isofit/isofit

- CONTRIBUTING.rst
- isofit/isofit.py
- isofit/rt_modtran.py
- isofit/surf_emissive.py
I added an explicit policy for accepting pull requests and making releases.  I also included minor bug fixes related to radiance corrections, binary mode and emissive surfaces.  This pull request will test our code update procedure.
> Pull request acceptance policy

- .travis.yml
- CONTRIBUTING.rst
- setup.py
Added a new condition using `$TRAVIS_EVENT_TYPE != cron` per blog instructions online.  Documentation regarding these conditions seems incomplete in places.
> Updated deploy on settings to deploy when type is not cron

- isofit/geometry.py
- isofit/instrument.py
- isofit/inverse.py
- isofit/rt_lut.py
- isofit/rt_modtran.py
- utils/instmodel.py
Useful for tutorial materials and class laboratories that may not have licenses (or want to wait for MODTRAN runs).
> Configuration can override automatic LUT rebuild

- isofit/inverse_simple.py
- setup.py
This subsumes and includes Nimrod's intended change.
> Update to sequential inversion method (used for initial guesses, etc.)

- isofit/__init__.py
- isofit/core/common.py
- isofit/core/inverse_mcmc.py
- isofit/radiative_transfer/look_up_tables.py
- recipe/meta.yaml
Submitted on behalf of Jouni Susiluoto (JPL statistics Postdoc).  
- Fast, stable matrix inversions via eigendecomposition.
- Removed lots of vestigial code in common.py
> Jouni's Magic (stable, fast matrix inversions)

- isofit/radiative_transfer/radiative_transfer.py
> Bug fix in radiative_transfer.py

- isofit/core/instrument.py
- isofit/inversion/inverse_simple.py
- Fix nan when transm is 0 in inverse_simple.py
- Fix nan from negative data in parametric nedl calculation
> Fixes nans

- isofit/surface/surface_thermal.py
This correctly indexes the surface state vector to get the surface temperature in the message.
> Surface thermal bug

- isofit/utils/apply_oe.py
- Deterministic LUT naming
- Surface model selection
- PRISM sensor support
> Minor upgrades to apply_oe.py

- examples/20151026_SantaMonica/configs/prm20151026t173213_D8W_6s.json
- examples/20151026_SantaMonica/configs/prm20151026t173213_D8p5W_6s.json
- examples/20151026_SantaMonica/configs/prm20151026t173213_D9W_6s.json
- examples/20151026_SantaMonica/configs/prm20151026t173213_D9p5W_6s.json
- examples/20171108_Pasadena/configs/ang20171108t173546_darklot.json
- examples/20171108_Pasadena/configs/ang20171108t173546_horse.json
- examples/20171108_Pasadena/configs/ang20171108t184227_astrogreen.json
- examples/20171108_Pasadena/configs/ang20171108t184227_astrored.json
- examples/20171108_Pasadena/configs/ang20171108t184227_beckmanlawn-libradtran.json
- examples/20171108_Pasadena/configs/ang20171108t184227_beckmanlawn-oversmoothed.json
- examples/20171108_Pasadena/configs/ang20171108t184227_beckmanlawn-undersmoothed.json
- examples/20171108_Pasadena/configs/ang20171108t184227_beckmanlawn.json
- examples/20190806_ThermalIR/configs/joint_isofit_with_prof_WATER_nogrid.json
- examples/20190806_ThermalIR/run_example_modtran_one.py
- isofit/core/fileio.py
- isofit/radiative_transfer/libradtran.py
- isofit/radiative_transfer/look_up_tables.py
- isofit/radiative_transfer/modtran.py
- isofit/radiative_transfer/radiative_transfer.py
- isofit/radiative_transfer/six_s.py
- isofit/utils/apply_oe.py
This avoids an execution path where apply_oe.py attempts to reference an undefined variable.
> Minor fix for undefined max_water

- isofit/utils/apply_oe.py
passed missing empirical_line parameter into presolve config
> apply_oe presolve config correction

- isofit/core/fileio.py
Small bug in fileio, not sure when it go introduced, but found it during debugging.
> fix all nodata fileio return bug

- isofit/core/isofit.py
The order got messed up so rows and cols were None even when set in the object initialization.
> Fix bug with row column input

- isofit/configs/sections/radiative_transfer_config.py
- isofit/radiative_transfer/look_up_tables.py
- isofit/radiative_transfer/modtran.py
- isofit/radiative_transfer/six_s.py
- isofit/utils/apply_oe.py
Updated documentation, sixs modification to work without install if output files exist, apply_oe bug fixes, updated MODTRAN random stalling (to help with license server issues on multi-node machines).
> misc. updates

- isofit/configs/sections/implementation_config.py
- isofit/configs/sections/output_config.py
- isofit/core/fileio.py
- isofit/core/isofit.py
- isofit/inversion/inverse.py
- isofit/utils/apply_oe.py
- permits user-defined ray temporary directories
- apply_oe.py writes atmospheric coefficients for each segment, will permit fancy field interpolation methods later
- fixed atm. coefficient output
> multi-user ray support, fix for atmospheric coefficient output files

- isofit/core/fileio.py
- isofit/core/instrument.py
Addressing points raised in #128.
> Meas badvalue fix

- docs/source/conf.py
- docs/source/custom/best_practices.rst
- docs/source/index.rst
"Best practices" section suggesting reasonable defaults
> new documentation

- isofit/core/isofit.py
Adding cleanup back in to address #130, was removed by accident during refactor.
> added del function back in to isofit core

- isofit/configs/sections/inversion_config.py
- isofit/configs/sections/radiative_transfer_config.py
- isofit/core/isofit.py
- isofit/inversion/inverse.py
- isofit/inversion/inverse_mcmc.py
- isofit/radiative_transfer/libradtran.py
- isofit/radiative_transfer/look_up_tables.py
Per our discussions, I wanted to finally create this pull request so that we can start a dialogue about the code and, if it looks OK, get it into the master branch (and make it easier for others to find and use). The original branch for this is at https://github.com/ashiklom/isofit/tree/py-hypertrace, but to avoid flooding your repo with lots of experimental commits, I created this branch with a cleaner history.
The workflow itself is confined to commit f29375d. The remaining changes include some relevant fixes or improvements to Isofit itself, including:
1. Catch value errors in inversions of individual pixels as part of the Isofit workflow (0a82416). This allows inversions to be robust to images with a handful of bad pixels.
2. Allow LibRadtran to use prescribed sun-sensor geometry …
> Pre-Hypertrace Isofit revisions

- isofit/configs/sections/statevector_config.py
- isofit/inversion/inverse_simple.py
- isofit/radiative_transfer/modtran.py
- isofit/surface/surface_multicomp.py
This PR adds air temperature as a possible state vector parameter when using MODTRAN. The state vector parameter name is AIRT_DELTA_K. It uses that parameter from MODTRAN that adds a constant offset to the air temperature profile.
This PR also changes the multicomponent surface reflectivity upper bound from 10 to 1.
> Adds air temperature as a state parameter

- isofit/core/instrument.py
Fixes a divide-by-small-number issue with low radiances in the instrument noise model.  Fixes #194
> noise updates

- isofit/utils/apply_oe.py
- isofit/utils/empirical_line.py
- isofit/utils/extractions.py
- isofit/utils/segment.py
Updates apply_oe.py to allow an un-specified sensor by passing "NA-%Y%m%d", which supplies the required date of acquisition.
Also applies bug-fix to extractions.py, handling cases where labels are not perfectly sequential (possible depending on the parallelization and presence of nodata in segment.py, and certainly possible from an externally supplied segmentation).
Enforces strict monotonic increase in segmentation generation as well.
> Unknown sensor option and extraction/segmentation bug fix

- isofit/utils/apply_oe.py
Add the emit sensor into sensor list of apply_oe.
> add emit sensor

- isofit/utils/empirical_line.py
- isofit/utils/extractions.py
- isofit/utils/segment.py
I was overzealous in my copy-and-paste of ray config updates for several utils.  This patch fixes the recently introduced issues.
> ray config patch

- examples/py-hypertrace/.gitignore
- examples/py-hypertrace/README.md
- examples/py-hypertrace/prepare_example_hypertrace_data.sh
- examples/py-hypertrace/slurm/run_hypertrace_sbatch.sh
- examples/py-hypertrace/slurm/run_hypertrace_sbatch_broadcast.sh
- examples/py-hypertrace/slurm/set_ray_params.py
- examples/py-hypertrace/workflow.py
Updated workflow.py to provide a text file of the different simulation experiments. Provided prepare_example_hypertrace_data.sh to make it easier to obtain the example datasets, noise, and surface files.
> Added two SLURM examples and other small changes

- README.rst
> Zenodo DOI badge

- examples/py-hypertrace/configs/example-srtmnet.json
- examples/py-hypertrace/hypertrace.py
- isofit/configs/configs.py
- isofit/configs/sections/implementation_config.py
- isofit/configs/sections/input_config.py
- isofit/configs/sections/output_config.py
- isofit/configs/sections/radiative_transfer_config.py
- isofit/configs/sections/surface_config.py
- isofit/core/common.py
- isofit/core/fileio.py
- isofit/core/isofit.py
- isofit/radiative_transfer/look_up_tables.py
- isofit/radiative_transfer/radiative_transfer.py
- isofit/surface/surface.py
- isofit/test/data/config_forward.json
- isofit/test/test_libradtran.py
- isofit/utils/apply_oe.py
Starting up an IO / ray interface refactor.  Should decrease ray dependency, and make things more 'pythonic' - goal is to open up different future IO strategies, allow better use of IO buffers, and decrease poor core utilization through an actor-based parallelization.
> IO refactor

- README.rst
Since we're starting to use badges, add docs badge to main rst.
> add docs badge

- docs/source/custom/bibliography.rst
- isofit/radiative_transfer/sRTMnet.py
- isofit/utils/apply_oe.py
Update references internally and in bibliography.
> reference updates

- examples/20171108_Pasadena/configs/ang20171108t184227_beckmanlawn-libradtran.json
- isofit/core/fileio.py
- isofit/inversion/inverse.py
A few bug fixes in the IO for radiance calculations.
Also a small update to the libradtran config.
> Io corrections

- isofit/inversion/inverse_simple.py
- isofit/radiative_transfer/modtran.py
- isofit/surface/surface_thermal.py
also allows unsorted early radiance bands
> updates to allow some more flexible thermal conditions

- isofit/utils/apply_oe.py
Minor update to apply_oe to facilitate utilizing an h5 emulator file.
> emulator format update

- isofit/utils/surface_model.py
@davidraythompson , this is ready for your review.
> update to surface_model utility to facilitate repeatable solutions

- isofit/utils/apply_oe.py
Very slight path updates for apply_oe, making the model discrepancy a default.
> slight path updates in apply_oe for EMIT

- isofit/utils/analytical_line.py
- isofit/utils/apply_oe.py
small updates for extra logging, EMIT inversion windows, and a check to prevent analytical inversions of nodata
> small analytical inversion updates

- isofit/core/fileio.py
- isofit/utils/analytical_line.py
- isofit/utils/atm_interpolation.py
Update the envi bbls, so they are a) correct when using the analytical_line, and b) fully 1 when not to avoid annoying warning messages.  @davidraythompson, ready for your review.
> Bad Band Fix

- .git-blame-ignore-revs
- .github/workflows/linter.yml
- isofit/utils/analytical_line.py
- isofit/utils/apply_oe.py
- isofit/utils/empirical_line.py
- isofit/utils/multisurface_oe.py
- isofit/utils/template_construction.py
We missed updating the linter workflow when we changed branch names. This should correct it so new PRs are checked for Black styling. 
This also corrects PR #322 not applying Black, see [here](https://github.com/isofit/isofit/pull/322/files#diff-b8514b2b362d67c2e09ad89b0508a8df55d0571b80d2dacc2dc85ebb68b6cd8f).
#336
> Black Workflow

- docs/source/custom/CONTRIBUTING.rst
Simplifies release steps based on updates in #332.
> simplified release steps

- isofit/__init__.py
- isofit/inversion/inverse_simple.py
- isofit/utils/ewt_from_reflectance.py
Adds utility to do flight-line scale EWT / CWC calculation from reflectance, using @unbohn's methods previously added.
@jammont - should this be using cli instead of argparse now?
> simple ewt from reflectance.py

- Dockerfile
Followup improvements to the Dockerfile implemented by PR #372.
WIP
- Added `ENV SHELL=/bin/bash` to fix the Jupyter terminal
- Changed `unpinned.yml` back to `environment_isofit_basic.yml` -- the former was a temp fix before PR #366 was merged
> Docker Improvements

- isofit/core/geometry.py
Simple PR to update the `geometry.path_length` to be in kilometers instead of meters.
> PathLength Meters to Kilometers

- isofit/__init__.py
- isofit/configs/sections/radiative_transfer_config.py
- isofit/core/geometry.py
- isofit/core/instrument.py
- isofit/radiative_transfer/look_up_tables.py
- isofit/radiative_transfer/modtran.py
- isofit/radiative_transfer/radiative_transfer_engine.py
- isofit/test/test_geometry.py
- isofit/test/test_lut.py
- isofit/utils/luts/__init__.py
- isofit/utils/luts/channel_read.py
- isofit/utils/luts/lut.py
- isofit/utils/luts/modutils.py
Refactor of codebase to support HDF5 LUT configs, and more general geometry / radiative transfer engine keys along the way.
> LUT refactor

- isofit/core/geometry.py
- isofit/radiative_transfer/radiative_transfer_engine.py
Adding suggested changes from the team:
- removes a lot of the commented out code in geometry
- adds datetime optional input to geometry
- creates standard output filenames...transm is now split into 4 components, and transm_down_dif can be the old transm as needed (per team discussion).
@unbohn - if you and @jammont are happy, please merge away (and modify as needed).
@jammont - note that I didn't update modutils.
> rte output name updates

- isofit/utils/luts/rte.py
- isofit/utils/luts/zarr.py
This PR will be implementing NetCDF for LUTs
WIP
> NetCDF for LUTs

- isofit/utils/luts/lut.py
- isofit/utils/luts/lututils.py
- isofit/utils/luts/netcdf.py
- isofit/utils/luts/rte.py
- isofit/utils/luts/zarr.py
Part 2 of #386 that properly implements the NetCDF interface similar to the Zarr interface implemented in the previous PR.
> LUT NetCDF part 2

- isofit/radiative_transfer/libradtran.py
- isofit/radiative_transfer/modtran.py
- isofit/radiative_transfer/radiative_transfer.py
- isofit/radiative_transfer/radiative_transfer_engine.py
- isofit/radiative_transfer/six_s.py
- isofit/test/test_lut.py
This PR moves physics-based RT functions from the engine modules to `radiative_transfer.py`. This removes redundant lines of code and aggregates physical models in one place.
> Refactoring of physics-based RT functions.

- isofit/radiative_transfer/modtran.py
- isofit/radiative_transfer/radiative_transfer.py
- isofit/radiative_transfer/radiative_transfer_engine.py
- isofit/test/test_lut.py
@pgbrodrick Here's a first small test case for building and reading a LUT file using the new engine class. There's still much room for additions and refinements, but it provides an initial basis. Right now, the test fails due to multiple issues. I'll continue working on this during the next week, but feel free to modify and add stuff as we proceed.
@jammont Comments from your side are of course highly welcome as well!
> RT engine and LUT tests.

- isofit/radiative_transfer/modtran.py
- isofit/radiative_transfer/radiative_transfer.py
- isofit/radiative_transfer/radiative_transfer_engine.py
- isofit/radiative_transfer/six_s.py
Working on integrating individual RTEs...in the process, had to revise existing RTE.
@jammont - I implemented your suggestion for hanling ray.  Note the required netcdf append function (can be renamed as needed of course).
> Individual RTEs

- .github/workflows/example-testing.yml
- .github/workflows/py-hypertrace.yml
- .github/workflows/release.yml
- .github/workflows/utils-workflow.yml
- examples/image_cube/configs/basic_config.json
- examples/profiling_cube/small_chunk/configs/mlg.json
- examples/profiling_cube/small_chunk/configs/nds.json
- examples/profiling_cube/small_chunk/configs/rg.json
- examples/py-hypertrace/configs/example-srtmnet-ci.json
- isofit/utils/apply_oe.py
@pgbrodrick @jammont I'm currently working on updating and fixing both PyPi and conda package versions of ISOFIT. To avoid a failure of the automatic PyPi upload, I need updated GitHub workflows in the main branch, which will be implemented by this PR.
Upon review and acceptance, could any of you guys merge this in?
> Updates to GitHub workflows.

- .github/workflows/example-testing.yml
- .github/workflows/py-hypertrace.yml
- .github/workflows/release.yml
- .github/workflows/utils-workflow.yml
Based on @jammont's comments, this PR adds some more recent updates to the GitHub workflows to make them more stable. The [PyPi release workflow ](https://github.com/isofit/isofit/actions/runs/6801331076/job/18491917506) was still failing, but the changes proposed here will most likely fix it.
@jammont Could you review this and merge in after approval?
> More recent updates to GitHub workflows

- .github/workflows/example-testing.yml
- .github/workflows/py-hypertrace.yml
- .github/workflows/release.yml
- .github/workflows/utils-workflow.yml
- examples/image_cube/configs/basic_config.json
- isofit/utils/apply_oe.py
- setup.cfg
This PR adds recent updates of the GitHub workflows to the `dev` branch in order to align it with the current status of `main` (disobeying our code of conduct, I initiated a merge of these changes directly into `main` last week).
@pgbrodrick @jammont This should be a quick one. Could any of you merge it?
> GitHub workflow updates.

- isofit/utils/apply_oe.py
> Length 1 elevation LUT protection

- .imgspec/apply_glt.py
- isofit/radiative_transfer/radiative_transfer.py
- isofit/utils/apply_oe.py
- isofit/utils/ewt_from_reflectance.py
- isofit/utils/template_construction.py
- recipe/environment_isofit_basic.yml
- setup.cfg
Per team conversations, remove the gdal dependency from the repo.
Does not remove gdal from hypertrace module loads for now, but that should not induce any issue.
> Remove GDAL

- isofit/utils/apply_oe.py
Addresses: #430.  @davidraythompson, for review.
> patch fix to read loc data

- isofit/utils/apply_oe.py
This is a patch for #437 in order to remove the out-of-sync automatic linting. Instead, this PR only adds the updates to `apply_oe.py`, and replaces #437.
> EnMAP support in apply_oe - patch.

- isofit/test/test_cli.py
- isofit/utils/template_construction.py
This PR fixes CI workflows that are still failing after merging #421. It's marked as a draft as it awaits the merge of #448, which provides a utility to download data and example files. Those are needed to resolve final issues with the CI workflows.
> CI workflow fixes

- isofit/test/conftest.py
- isofit/test/test_cli.py
- pytest.ini
> Fix unmarked test labeling

- .github/workflows/release.yml
* Updated release workflow by removing dependency on docker image.
* Deleted docker related section in release.yml.
> Updated release workflow (#450).

- isofit/utils/apply_oe.py
- isofit/utils/template_construction.py
Just add gao to the list of SUPPORTED_SENSORS and an `elif` clause to extract datetime and fid from a GAO/CAO radiance map. I've been meaning to do this for a while to save me having to re-implement each time I pull.
> Add gao as an instrument option for apply_oe

- isofit/utils/apply_oe.py
Added custom inversion windows for AVIRIS-3 to `apply_oe.py` utility, similar to EMIT.
> Added custom inversion windows for AVIRIS-3

- README.rst
This PR updates the `README.rst` with the major features from the upcoming 3x release.
> Major 3x release notes.

- .github/workflows/test-pip-package-ubuntu.yml
- .github/workflows/test-pythonpath-ubuntu.yml
- docs/source/custom/best_practices.rst
- examples/20190806_ThermalIR/configs/joint_isofit_with_prof_WATER_nogrid.json
- examples/profiling_cube/run_profiling.py
- examples/py-hypertrace/configs/example-calibration.json
- examples/py-hypertrace/configs/example-libradtran.json
- examples/py-hypertrace/configs/example-modtran.json
- examples/py-hypertrace/configs/example-srtmnet-ci.json
- isofit/radiative_transfer/modtran.py
- isofit/test/data/config_forward.json
- isofit/test/data/config_inversion.json
- isofit/test/test_examples.py
- isofit/test/test_hypertrace.py
The example workflows were marked to be expected failure. This oversight provided us false confidence that the test cases were passing when in reality they were still failing.
> Example workflows re-enabled

- isofit/core/common.py
Seeks to improve the memory efficiency of the VectorInterpolator class which is presently causing an explosion in memory usage in high dimensional cases
- Detect when the input data is a single unique value and skip most of the processing if so
> Interpolator Memory Improvement

- isofit/core/forward.py
- isofit/radiative_transfer/modtran.py
Soften the wavelength constraints introduced in #476 in order to address #486.
> Wavelength check updates

- isofit/configs/sections/radiative_transfer_config.py
- isofit/inversion/inverse_simple.py
- isofit/radiative_transfer/kernel_flows.py
- isofit/radiative_transfer/luts.py
- isofit/radiative_transfer/radiative_transfer.py
- isofit/radiative_transfer/radiative_transfer_engine.py
> Add the handling of flux quantities #2.

- docs/source/custom/CONTRIBUTING.rst
- isofit/radiative_transfer/luts.py
Add compression to netcdf files (keeps them from exploding in size with null values), and update maintainers list.
> Compression

- examples/py-hypertrace/hypertrace.py
- isofit/core/geometry.py
- isofit/radiative_transfer/luts.py
- isofit/radiative_transfer/modtran.py
- isofit/radiative_transfer/sRTMnet.py
- isofit/utils/apply_oe.py
- isofit/utils/template_construction.py
- recipe/environment_isofit_basic.yml
- setup.cfg
This simple patch fixes a bug introduced during refactoring for sRTMnet azimuth geometries.
> patch azimuth geometries

- isofit/radiative_transfer/engines/kernel_flows.py
- isofit/utils/template_construction.py
#488  moves the RT engines to a submodule. This fixes some missed import statements
> Fixed KF imports for the engines submodule

- isofit/core/common.py
- isofit/core/isofit.py
- isofit/radiative_transfer/luts.py
- isofit/wrappers/ray.py
Tweaks the cache of `common:VectorInterpolator` to support N many points instead of just 1.
> N Point VectorInterpolator Cache

- isofit/configs/sections/radiative_transfer_config.py
- isofit/radiative_transfer/radiative_transfer_engine.py
Detects duplicates in the lut_grid in two places:
- In the RTE config
- In RTE right before simulations
Closes #539
> Lut grid duplicates

- isofit/core/forward.py
Checks if the input `q` (which `reference_reflectance` is passed through to` is the wrong size and interpolates if needed.
> Handle wrong sized reference reflectance inputs

- isofit/radiative_transfer/engines/modtran.py
> Removed custom FileExistsException

- isofit/utils/surface_model.py
Click implementation for the surface_model.py wasn't working, this fixes it. Changed optional `--` options from `argument` to `option`, and required options removed `--`
Closes #SlackConversation
> Surface Model CLI

- isofit/configs/sections/surface_config.py
- isofit/surface/surface_multicomp.py
- isofit/utils/analytical_line.py
Enforces bounds on output RFLs to be zero and not negative except in the cases of the fill value `-9999` and `-0.01`
Closes #325
> Negative RFLs

- isofit/__init__.py
- isofit/debug/__init__.py
- isofit/debug/ray_bypass.py
- isofit/test/test_ray_bypass.py
Fixes:
Closes #555
Closes #549
> ISOFIT debug fixes

- .github/workflows/test-pip-package-ubuntu.yml
- .github/workflows/test-pythonpath-ubuntu.yml
- isofit/data/cli/__init__.py
Adds support for Python 3.12.
Closes #564
> Python 3.12

- isofit/radiative_transfer/engines/modtran.py
- isofit/radiative_transfer/radiative_transfer_engine.py
I nuked the last PR. My attempts to rebase went awry. Wanted to make sure commit history was clean.
> Fixed IndexError when building Modtran LUT

- isofit/utils/apply_oe.py
Short PR to support the ability to pass specific inversion windows in and bypass the sensor or global defaults.
> Inversion windows update

- CITATION.cff
- isofit/__main__.py
- isofit/test/test_cli_machinery.py
- isofit/utils/__init__.py
- isofit/utils/reconstruct.py
I use this a bunch when looking at data. We talked about adding the hooks within Isofit to do this. I kept it as a standalone module for now. Could easily wrap it into applyOE as an argument and routine if it proves to be useful/needed.
> Added function and cli tool to reconstruct subs files to full resolution

- isofit/radiative_transfer/radiative_transfer.py
> Added Logger definition to radiative_transfer.py

- isofit/inversion/inverse_simple.py
- isofit/radiative_transfer/radiative_transfer.py
This PR adds a function to `RadiativeTransfer` to do the conversion from radiance to transmittance and the other way round.
> Add function to do radiance <-> transmittance conversion.

- isofit/core/common.py
- isofit/core/instrument.py
- isofit/radiative_transfer/engines/modtran.py
- isofit/radiative_transfer/engines/six_s.py
- isofit/radiative_transfer/luts.py
- isofit/radiative_transfer/radiative_transfer_engine.py
small 6s and modtran changes for wavelengths and angles
> RTM bug fixes

- isofit/inversion/inverse_simple.py
- isofit/radiative_transfer/radiative_transfer.py
@jammont This fixes the issue with the conversion functions. Feel free to merge as soon as checks have passed.
> Patch to RT conversion functions.

- isofit/configs/sections/radiative_transfer_config.py
- isofit/radiative_transfer/radiative_transfer_engine.py
Fixes some exceptions being raised that caused sections of the configuration not being checked properly. Addresses a few downstream checks that haven't been triggered in awhile but are now outdated
> RTE Configuration Errors

- isofit/utils/apply_oe.py
- isofit/utils/template_construction.py
Replace #550 with a trimmed down PR and small tweaks.
> basic tanager syntax

- isofit/utils/apply_oe.py
Small changes to fix silly self-induced errors for tanager.
> tanager patches

- isofit/inversion/inverse_simple.py
closes #576 , by saving the refractive index of water Excel file to a CSV. 
I've opened up a similar pull request in ISOFIT-Data that brings in this new file.
> swap path for csv

- isofit/utils/apply_oe.py
> Directory Initialization

- isofit/radiative_transfer/radiative_transfer_engine.py
> remove deprecated rte coszen call

- isofit/inversion/inverse_simple.py
This is a stopgap patch to address #705. 
A better solution would be to leverage RT.calc_RT_quantities, but this serves to get us back operating in the short term.
> heuristic patch

- isofit/core/common.py
- isofit/core/fileio.py
- isofit/core/geometry.py
- isofit/core/instrument.py
- isofit/core/units.py
- isofit/inversion/inverse_simple.py
- isofit/radiative_transfer/engines/modtran.py
- isofit/radiative_transfer/engines/sRTMnet.py
- isofit/radiative_transfer/engines/six_s.py
- isofit/radiative_transfer/radiative_transfer.py
- isofit/radiative_transfer/radiative_transfer_engine.py
- isofit/utils/apply_oe.py
- isofit/utils/template_construction.py
PR to handle unit and conversion consistency throughout the code.  See #711 .
> Units and conversions

- isofit/radiative_transfer/luts.py
Adds the ISOFIT version to the LUT attributes dict on creation
> LUT Version Tags

- isofit/debug/resource_tracker.py
- isofit/utils/apply_oe.py
Added a new module under `debug` called `resource_tracker.py` which implements some utilities to track a system's memory and CPU resources.
This'll be used by isoplots to plot the resources in real time and connect the log file to this to track important events, such as if memory spikes during certain operations, etc
> Resource Tracker

- isofit/utils/wavelength_cal.py
Quick patch to restore functionality to wavelength_cal in multisurface mode.
> Wavelength multisurface fix
