isofit/isofit

- isofit/inverse_simple.py
- isofit/surf_multicomp.py
- setup.py
This permits the multicomponent surface to avoid recalculating component memberships with each iteration.  Instead it uses the iteration-zero result for the entire retrieval.
> Stability improvements for multicomponent surface model

- isofit/radiative_transfer/look_up_tables.py
This commit fixes a sign error in the derivatives calculation in look_up_tables.py. See this file for the equation details: [isofit_sign_error.pptx](https://github.com/isofit/isofit/files/4123600/isofit_sign_error.pptx)
> Fixes sign error in drdn_dRT in look_up_tables.py

- isofit/radiative_transfer/look_up_tables.py
There are two bugs fixed here:
1. Correctly assign transup to the transup_interp variable (issue #60)
2. Correctly use transupe instead of transup
> Fix bugs in look_up_tables.py

- isofit/core/common.py
- isofit/radiative_transfer/look_up_tables.py
This commit has a small change to the VectorInterpolator class that dramatically improves its performance (~15x). Removing the loop over the spectral dimension and allowing the scipy function to handle it makes the loop run at native speeds. This commit then uses VectorInterpolate instead of the JIT version as it is simpler to read and understand.
Based on the simple timings below, it seems like all of the JIT code could be removed for simplicity without any performance loss. I didn't do that here though.
The following are simple timings using %timeit on the Pasadena darklot example.
Original VectorInterpolatorJIT with jit_enabled = True: 6.8 s
Original VectorInterpolator with jit_enabled = False: 96 s
New VectorInterpolator with hit_enabled = False: 6.5 s
> Optimized vector interpolator

- isofit/core/common.py
- isofit/core/inverse_grid.py
- isofit/core/inverse_simple.py
- isofit/surface/surface_thermal.py
Two main changes here to the thermal parts:
1. Switch from using the conditional mean for the TIR surface reflectivity initialization to using the cluster mean. The cluster is chosen based on the initial, heuristic inversion of the VSWIR.
2. Make the surface temperature prior variance a config parameter instead of being hard coded. Also make the emissivity assumed for the initial temperature estimate a config parameter too. Both parameters are also given default values that seem to work ok.
> New thermal surface and t init

- isofit/core/isofit.py
Rework multiprocessing workflow to minimize redundant pickling.  Test case using 100 spectra (426 band), and 10 cores:
Prior: 
Parallel inversions complete.  89.84578514099121 s total, 1.1130182661665675 spectra/s, 0.11130182661665675/spectra/core
After change:
Parallel inversions complete.  34.05124616622925 s total, 2.9367500828553013 spectra/s, 0.2936750082855301/spectra/core
Speedup factor: 2.64
> Multiprocessing rework

- isofit/core/isofit.py
- isofit/radiative_transfer/look_up_tables.py
- isofit/radiative_transfer/modtran.py
- isofit/utils/apply_oe.py
Patch fix to handle the case where the H2OSTR exceeds 100% RH or 5x the original value.  If a lut_grid is specified that exceeds what MODTRAN can model, an exception is thrown.  This is to safeguard against subsequent Jacobian miscalculations and ultimately bad inversions, for these cases.
If you intentionally want to override the H2OSTR maximum, you can either change to a custom, user profile, or set the ATMOSPHERE->H2OOPT option to '+'.
apply_oe has been updated to use the maximum atmospheric water value accepted by MODTRAN for running the presolve.
> Modtran h2o bounds

- isofit/utils/apply_oe.py
- isofit/utils/surface_model.py
This adds some extra fields to the surface model file.  It facilitates a new technique that I've been working on for a while with Niklas Bohn (GFZ) in which we estimate surface properties via joint correlation with surface reflectance parameters.  In the past, we have added these properties as "unobserved reflectance channels."  But this is a bit awkward.  Here, I add this information to the surface model, so that the parameter inference can be performed as a postprocessing step conditioned on the reflectance solution.  This would allow the ISOFIT reflectance model to use the same wavelength grid as the instrument, simplifying the rest of the code.
> Surface model permits correlated attributes

- isofit/configs/sections/surface_config.py
- isofit/inversion/inverse.py
- isofit/utils/apply_oe.py
I think that a few minor changes might improve stability, particularly for new users.
1) Make the "Euclidean" distance metric for component selection the default choice in our multicomponent surface models.   I can't remember a time when it made a blatantly unreasonable choice.  In contrast, the Mahalanobis methods can occasionally be tricked (by near-singular covariances?) into selecting an unrealistic model.  This results in very strange and difficult-to-diagnose error conditions - the spectrum converges, but to an answer which is obviously wrong.  Switching to Euclidean selection immediately solves the problem.
2) Increase the precision tolerance for optimization convergence, at the suggestion of Jay Fahlen.
3) Artificially broaden the range of H2O vapor resulting from apply_oe.py's …
> Stability upgrades

- isofit/radiative_transfer/modtran.py
- isofit/utils/apply_oe.py
This fixes a problem which occurred when running MODTRAN on macOS 10.14.6 for the H2O bound test. Reading the tp6 file fails with a codec error. @pgbrodrick
> Avoiding codec error when reading tp6 file in water vapor bound test

- docs/source/requirements.txt
- isofit/inversion/inverse.py
Patches a bug fix in inversion_grid, for multiple preseed values, enabling the grid to work across multiple dimensions.  Also re-orders the preseed so it is updated *after* the initial guess, more appropriately.
Additional requirement fix for documentation.
> Inversion fix

- isofit/configs/configs.py
Addresses issue #126 
This was tested by comparing the results of two otherwise identical runs. The first used a standard json input and the second used the same input config but converted to yaml. Both produced the same retrieved state vector and final residual.
As json is a subset of yaml, I removed the json code altogether. I think also that we don't need any of the fancy python object stuff from yaml, so we can use yaml.safe_load because it's, er, safer.
> Json to yaml

- isofit/configs/sections/radiative_transfer_config.py
- isofit/inversion/inverse_simple.py
- isofit/radiative_transfer/radiative_transfer.py
Fixes two related problems. The first is that the code expects the radiative transfer engines to be in sorted wavelength order, but they weren't when the config input was not. This update puts them in order. The second is that the RadiativeTransfer.pack_arrays() function would attempt to look up nonexistent keys in the individual  RT engines's get() returns. This PR ensures that only those RTM quantities that are shared among all RT engines will be processed.
> Bug fix in radiative transfer

- isofit/inversion/inverse_simple.py
This PR adds the capability to do TIR-only retrievals. The change requires only a modification to the initialization in inverse_simple. When doing TIR, if VSWIR is present then use the VSWIR init to get an initial TIR reflectivity estimate. If VSWIR is not present, then simply assume a flat TIR emissivity spectrum of 0.97.
> Thermal only

- isofit/radiative_transfer/look_up_tables.py
- isofit/radiative_transfer/modtran.py
- isofit/utils/apply_oe.py
In some cases, Isofit changes directories in unexpected ways, which can
cause relative paths to fail when they really shouldn't. Ideally, the
Isofit executable should respect its current working directory as much
as possible. These changes try to more reliably undo working directory
changes when they happen:
- In two instances, we change directory just to execute a
`subprocess.call`. In these situations, we can just pass the `cwd`
argument to `subprocess.call` to achieve the exact same effect, but in a
way that is more robust to crashes midway through the command.
- In one other place, the directory change is more complicated, so I
added a call to `atexit.register(os.chdir, cwd)`. This basically tells
Python to run the `os.chdir(cwd)` command as soon as the function call
exits for _any_ …
> Sanitize directory changes

- docs/source/custom/bibliography.rst
- docs/source/index.rst
Adds bibliography, broken out by topic, addressing #152.  I'm not in love with the heading 'Extensions' - neither of those really extend the codebase...they're somewhere between applications and expansions.  Updated headers or additional manuscripts would be great, but I think breaking out by topic is important.
> adds bibliography

- isofit/utils/empirical_line.py
See #161.
Ray is configured identically to `isofit.py` -- i.e., the relevant options from the `implementation` config are passed to ray in the same way. The one exception is that the `n_cores` argument, if set to something other than `-1`, overwrites whatever is in the implementation config. This is intended to match the current behavior.
Also, I think the `isofit_config` argument documentation is inconsistent with how it's actually used (the function says it expects a dict, but the call in `apply_oe` passes a path, so I took the liberty of revising that too.
Feedback welcome!
> Use ray instead of multiprocess in empirical_line

- isofit/core/fileio.py
- isofit/utils/empirical_line.py
- isofit/utils/extractions.py
- isofit/utils/instrument_model.py
- isofit/utils/segment.py
- isofit/utils/surface_model.py
Addresses issue #163 by opening up input interleaves to be anything - does not address output interleave, though discussion indicated that was a lower priority providing the inputs were opened up.  Switches out transpose of BIL interleaves for forced bip-reads, which conveniently also runs (very slightly) faster based on a speed test.  
@davidraythompson, could you review when you get a chance?
> interleave update

- isofit/utils/surface_model.py
A simple parameter override simplifies scripting in large workflows.
Currently, the only way to build a surface model for a new wavelength grid is to write out a new .json formatted configuration file.  This minor change allows the surface_model() function call to overwrite wavelength file and output file locations, so we can create new surface models dynamically without having to parse/write a JSON file.
> Surface config override parameters simplify calling scripts

- isofit/utils/apply_oe.py
Small change to apply_oe to guarantee cleanup, avoiding multiple ray instances.
> apply_oe object cleanup

- isofit/utils/apply_oe.py
- isofit/utils/extractions.py
Adds support for parallel extractions.  Also adds some complexity to extraction masking for efficiency.
Target is primarily projected, diagonal (non-NS) acquisitions that otherwise have very slow and inefficient extraction times.   Serial extractions should still work as normal.  apply_oe is updated to utilize these changes.
Tested on several flight lines with no change other than speed.
@davidraythompson or @winstonolson , this is ready for your review.
> parallel extractions

- isofit/utils/apply_oe.py
Small changes to apply_oe to make the LUT spacing physically based.  Instead of specifying a number of grid points (e.g., 5), you specify a spacing length in meters (e.g. 200).  
Useful for applications across a range of flightlines spanning different elevational gradients.
Set elevation_lut_spacing_m to 0 to use a single elevation (exclude it from the LUT).  This is the default, as previously.
This type of LUT spacing could be implemented for the other components as well - if there's interest I'm happy to extend, but I wasn't sure if that would actually be desirable.  Very open to thoughts.
> elevation lut refinement

- isofit/configs/sections/inversion_config.py
- isofit/utils/apply_oe.py
I have been chasing a problem where the default settings fail to fully correct water vapor absorption features.  This is most obvious over bare soil.   It appears to be that the default convergence tolerance is too loose.  I tightened it back to 0.0001, confirming that (a) any less yields residual vapor features, and (b) further tightening does not change the solution. 
Also a bug fix in apply_oe.py to avoid aerosol out of bounds initialization errors.
> Aerosol LUT grid rounding fix, ftol discussion

- isofit/radiative_transfer/sRTMnet.py
- isofit/radiative_transfer/six_s.py
- isofit/utils/apply_oe.py
This update fixes a bug in sRTMnet, whereby some elements were left out of the statevector (elevation, for example).  Also prevents apply_oe from populating sRTMnet with elevations below sea level (as negative elevation units (in km) in 6s are treated as pressure units).
Range of LUT elements turn more reasonable, as demonstrated by the comparison:
previously:
with fix:
> sRTMnet patch

- .github/workflows/py-hypertrace.yml
- examples/py-hypertrace/.gitignore
- examples/py-hypertrace/README.md
- examples/py-hypertrace/configs/.gitignore
- examples/py-hypertrace/configs/example-calibration.json
- examples/py-hypertrace/configs/example-libradtran.json
- examples/py-hypertrace/configs/example-modtran.json
- examples/py-hypertrace/configs/example-srtmnet.json
- examples/py-hypertrace/hypertrace.py
- examples/py-hypertrace/summarize.py
- examples/py-hypertrace/workflow.py
- isofit/core/isofit.py
- Adds support for the sRTMnet MODTRAN emulator to Hypertrace. This is now treated as the default model, though LibRadtran is still supported.
- Adds support for the constellation calibration uncertainty analysis.
- Add a GitHub Action CI test for sRTMnet. Also, fix the old LibRadtran test.
- Update the README to reflect the new default.
> sRTMnet support for Hypertrace

- isofit/utils/extractions.py
This simple PR forces 0 to exist in the extractions utility, even if there are no 0's (nodata ID's) in the segmentation file.  Useful for applying the empirical line in map-space, even if derived in raw-space.  Also just a good safety precaution.
> null extractions

- isofit/configs/sections/implementation_config.py
- isofit/core/fileio.py
- isofit/core/isofit.py
- isofit/utils/apply_oe.py
- isofit/utils/empirical_line.py
- isofit/utils/extractions.py
- isofit/utils/segment.py
- Handles #215
- Fixes IO bug (instrument object reference)
- Updates ray imports to facilitate local_mode (note, in future this will need to be switched to ray.utils to keep up with ray 2.+)
- Adds checks inside apply_oe for file sizes of radiance, loc, and obs (since I keep mixing ortho'd and non-ortho'd files)
- Adds a 'task inflation factor', so that more than n_cores jobs are launched, hopefully preventing individual cores from being handled the bulk for the work.  Defaults to 10x
- Puts an int() safety cast on 1e6 factor inside apply_oe
> Various patch fixes

- .github/workflows/py-hypertrace.yml
- examples/py-hypertrace/README.md
- examples/py-hypertrace/configs/example-srtmnet-ci.json
- examples/py-hypertrace/configs/example-srtmnet.json
- examples/py-hypertrace/hypertrace.py
- isofit/core/common.py
- isofit/radiative_transfer/look_up_tables.py
Per the conversation between me, @pgbrodrick , and @serbinsh earlier, this ensures that forward simulations in Hypertrace do not use any interpolation, but instead pass the AOD and H2O directly to the atmospheric RTM. This allows us to explore the impacts of denser vs. coarser LUTs, and is generally the right thing to do.
Note that currently, this will fail with the following error:
```
ValueError: Only 1 value in LUT grid {}. 1-d LUT grids cannot be interpreted.
```
The easiest workaround for me is to just add another point to the LUT. That wastes a bit of computation (forces a minimum of 4 (2? Can I use a 2x1 grid LUT?) RTM evaluations for every forward model run), but doesn't require upstream changes to Isofit itself. Not the end of the world, and should mostly only impact CPU but not …
> Hypertrace forward runs should not interpolate on the LUT

- isofit/core/fileio.py
- isofit/radiative_transfer/six_s.py
- isofit/utils/apply_oe.py
Adjust emulator to work in high orbits.  Builds off suggestions from #244, but handles the possibility of altitude bing in the LUT.  Uses the 'cap-at-99' style approach.
> High orbit emulator

- examples/py-hypertrace/hypertrace.py
- examples/py-hypertrace/summarize.py
- isofit/core/common.py
- isofit/core/fileio.py
- isofit/utils/apply_oe.py
- isofit/utils/empirical_line.py
- isofit/utils/extractions.py
- isofit/utils/instrument_model.py
- isofit/utils/interpolate_atmosphere.py
- isofit/utils/remap.py
- isofit/utils/segment.py
- isofit/utils/surface_model.py
Updates all instances of file_name + '.hdr' throughout the codebase to use the envi_header function in common.py.  This lets files that use any of the following formats work:
filename & filename.hdr
filename.img & filename.hdr
filename.img & filename.img.hdr
> make envi header references safe and global

- isofit/radiative_transfer/modtran.py
Was reading the same column from the channel file twice, instead of reading column 14 and 15. This would have had an impact only on the multipart modtran case.
> Fix a little error in reading the channel file

- isofit/configs/sections/implementation_config.py
- isofit/core/isofit.py
- isofit/utils/empirical_line.py
- isofit/utils/extractions.py
- isofit/utils/segment.py
Addresses #251 by removing ray.services utilization.  This was a feature that had intended to circumvent the issues w/ running ray while a VPN was connected, but the strategy is now deprecated anyway, and also causes dependency issues.
Also adds an option to run isofit in debug mode, which circumvents ray but still utilizes the worker class.  In debug mode, spectra are inverted using only one core.
To be done: 
- investigate if there's an easy VPN circumvention strategy that works w/ ray 1.8.0, and
> Ray updates

- isofit/configs/sections/implementation_config.py
- isofit/core/isofit.py
- isofit/utils/empirical_line.py
- isofit/utils/extractions.py
- isofit/utils/segment.py
- sets ray dashboard as parameter, defaults to false
- adds _temp_dir back to main isofit init
Also worth considering is setting RAY_worker_register_timeout_seconds to a higher value - 400 is recommended.  This is excluded as it should be run before the very first ray instance is run, but could also be passed into each utility separately.
> Ray dashboard

- examples/20151026_SantaMonica/configs/prm20151026t173213_D8W_6s.json
- examples/20151026_SantaMonica/configs/prm20151026t173213_D8p5W_6s.json
- examples/20151026_SantaMonica/configs/prm20151026t173213_D9W_6s.json
- examples/20151026_SantaMonica/configs/prm20151026t173213_D9p5W_6s.json
The Santa Monica example runs failed due to an outdated radiometry correction file given in the configs. This should now be fixed.
> Updated path to radiometry correction file in configs for Santa Monica example.

- docs/source/custom/installation.rst
This adds updated installation instructions for installing ISOFIT using mamba. Previously, the installation failed when using mamba installed via conda instead of using mini- or mambaforge since the installer was not searching for ISOFIT on the conda-forge channel.
> Update installation instructions for using the mamba installer.

- isofit/test/test_common.py
This adds the fix of a ValueError in test_common.py to prevent future failure of the main test workflow. I encountered the problem in my fork yesterday. The PR fixes the following error:
```
def test_combos():
inds = np.array([[1, 2], [3, 4, 5]])
ValueError: setting an array element with a sequence.
The requested array has an inhomogeneous shape after 1 dimensions.
The detected shape was (2,) + inhomogeneous part.
```
> Fix of ValueError in test_common.py to prevent failure of main test.

- isofit/core/forward.py
- isofit/inversion/inverse.py
- isofit/surface/surface.py
- isofit/surface/surface_glint.py
- isofit/surface/surface_lut.py
- isofit/surface/surface_multicomp.py
This PR implements a separation of surface state vector indexes within the forward class to cover cases where we retrieve additional non-reflectance surface parameters, such as sun glint for water surfaces or liquid water over vegetated pixels. This also fixes #315.
> Separation of surface state vector indexes.

- .dockerignore
- Dockerfile
- docs/source/custom/docker.rst
- docs/source/index.rst
- isofit/radiative_transfer/modtran.py
<h1>Description</h1>
Updates the Dockerfile to build an image that includes ISOFIT dependencies. Notably, this image includes:
- 6S
- sRTMnet
- ISOFIT
This PR touches #314.
The image comes with three preinstalled virtual environments using micromamba:
- `isofit` - The default environment that has ISOFIT installed alongside all of its dependencies.
- `test` - The testing environment that does not include ISOFIT but does include its dependencies.
- `nodeps` - An additional testing environment that does not include ISOFIT or its dependencies. This is primarily used for testing the installation process of ISOFIT.
`isofit` is the default environment; `test` will be used for our CI/CD pipeline. 
<h1>Changes</h1>
- ✨ New addition
- 🐛 Resolved a bug
- 🗒️ Documentation
<table>
<tr>
<th></th> …
> ISOFIT Docker

- .imgspec/apply_glt.py
- isofit/__init__.py
- isofit/core/isofit.py
- isofit/radiative_transfer/look_up_tables.py
- isofit/radiative_transfer/sRTMnet.py
- isofit/test/test_wray.py
- isofit/utils/analytical_line.py
- isofit/utils/atm_interpolation.py
- isofit/utils/empirical_line.py
- isofit/utils/extractions.py
- isofit/utils/segment.py
- isofit/wrappers/ray.py
Description
-
This is a patch for the Ray wrapper (and future wrappers) to properly respect the wrapper's environment flag. 
Problem
-
Early developments of the `ray` wrapper (`wray`) had it as an object that implemented `__getattribute__` to intercept all getattr calls and check if `DEBUG` is enabled or not. Depending on the flag, the object would either return our internal emulator functions or return the getattr of `ray`. 
Eventually we decided to remove config-defined debug flags in favour of environment variable flags. As such, to reduce implementation complexity, `wray` was converted from a class to a module. This module lost the `__getattribute__` functionality, thereby causing `wray` to always be enabled, essentially. 
Solution
-
Modules do not support `__getattribute__` (despite …
> Wrapper Patch

- isofit/__init__.py
The automatic PyPi upload workflow uses `setup.py` to build both distribution and wheel, and assigns the version number as given by `setup.py` to the upload file name. As the version number in `setup.py` is controlled by the ISOFIT `__init__`, the workflow failed due to an outdated version number in the `__init__`, producing the following error:
`Uploading isofit-2.9.8-py3-none-any.whl`
`HTTPError: 400 Bad Request from https://upload.pypi.org/legacy/`   
`File already exists.`
To ensure a successful upload, we have to update the version number in the ISOFIT `__init__` manually before publishing a new release.
@pgbrodrick Could you merge this in and then publish a new release with the tag `v2.9.9.2`? This PR updates the version number in the `__init__` to `2.9.9.2`, so that the workflow …
> Automatic PyPi Upload Patch #2

- isofit/utils/apply_oe.py
This PR directly addresses issue #368. 
The reason Ray fails to startup in apply_oe when executed from the CLI is because the click argument for it was wrongly set as an integer type and defaulted to `0`. 
The root of the problem is that the ISOFIT configuration module will typecast any value of `ray_temp_dir` to `str` because that's the type the value is supposed to be. Unless the value object explicitly prevents a `str()` cast, there's no warning/indication that this may cause issues. Since click was setting `ray_temp_dir = 0`, ISOFIT converts the value to `"0"` then passes it to [ray.init](https://github.com/isofit/isofit/blob/main/isofit/core/isofit.py#L86). 
Ray will not initialize with `ray.init(_temp_dir="0")`. Additionally, Ray would have raised an exception describing that this …
> Ray Timeouts

- Dockerfile
Remake PR of #372 due to some git base issues. This now only includes the Dockerfile changes.
Original PR text below
---
<h1>Description</h1>
This is a second take on the official Docker image for ISOFIT. This image differs from the first with the following:
- Replaced base image `mambaorg/micromamba:latest` with `rayproject/ray:2.4.0-py310-aarch64`
- This is Ray's official image and comes with conda installed already. To gain the benefits of mamba, the `conda-libmamba-solver` is installed before installing ISOFIT
- This stabilizes Ray significantly
- Default user is `ray` instead of `root` which is a better practice
- Removed test environment to reduce bloat
- Sets up a Jupyter-lab server and executes when the Docker is run
- Simplifies the install and usage for the image
This image has …
> Dockerfile v2

- isofit/inversion/inverse_simple.py
- isofit/utils/ewt_from_reflectance.py
- setup.cfg
This PR adds a few updates to the EWT inversion from reflectance command line tool.
- replaced the hardcoded number of workers with the number of cores, if specified
- added the option `--ewt_limit` to set the upper detection limit of EWT
- added the option `--plot_map` to plot and save an image file of the inverted EWT map on runtime
> Updates to EWT inversion from reflectance

- isofit/radiative_transfer/modtran.py
For running in multi-transmittance mode, the current MODTRAN config file uses the `["SURFACE"]["SURREF"]` keys to set a constant surface reflectance of 0.0, 0.1, and 0.5.
However, this mode is only compatible with `"SURFTYPE": "REFL_CONSTANT"`. Since we use `"SURFTYPE":  "REFL_LAMBER_MODEL"`, this setting has no effect and both ground reflected and multiple scattered radiance don't change between the three different reflectance cases (see pp. 72-75 of MODTRAN6 manual).
This PR updates the MODTRAN config file to use`LAMB_CONST_xx_PCT`  spectral albedo models from MODTRAN's spec_alb.dat file, with `xx` being the constant reflectance in percent, in case the three albedo method is applied to separate direct and diffuse downward transmittance.
> Fix of MODTRAN three albedo method

- isofit/utils/apply_oe.py
Hello ISOFIT maintainers! 👋 
When running `pytest` on both the `main` and `dev` branches, I noticed that the tests in `test/test_cli.py` fail consistently with the same error:
```
Datetime object could not be obtained. Please check file name of input data.
```
(See example error log [here](https://github.com/isofit/isofit/actions/runs/6618204928/job/17976120284#step:6:68).)
The failures appear to be caused by a bug in apply_oe's if-else logic which causes a ValueError to be raised for any AVIRIS-NG data set. I believe this PR should fix the issue.
> Fix test failures in `test_cli.py`

- isofit/utils/apply_oe.py
GitHub Actions CI currently shows a ❌ for every commit because the `black` formatting test fails.
This obviously isn't an important problem, but this PR fixes the issue so we can expect to see a ✅ in future PRs.
> Fix `black` CI failure

- examples/20171108_Pasadena/configs/ang20171108t184227_multimodtran.json
This updates the surface reflectance characterization in the multi MODTRAN template to fix the example workflow.
> Fixes multi MODTRAN template for Pasadena example.

- recipe/environment_isofit_basic.yml
- setup.cfg
ISOFIT currently requires a specific version of `protobuf`. This is causing a dependency conflict. For example:
```bash
$ git clone -b dev https://github.com/isofit/isofit.git
$ python -m venv tmpenv
$ source tmpenv/bin/activate
$ pip install ./isofit
ERROR: Cannot install isofit, isofit==2.10.1 and tensorflow because these package versions have conflicting dependencies.
The conflict is caused by:
isofit 2.10.1 depends on protobuf~=3.19.0
ray 2.5.1 depends on protobuf!=3.19.5 and >=3.15.3
tensorflow-macos 2.13.0 depends on protobuf!=4.21.0, !=4.21.1, !=4.21.2, !=4.21.3, !=4.21.4, !=4.21.5, <5.0.0dev and >=3.20.3
```
Can we remove `protobuf` as a dependency? It is not being imported by any ISOFIT code.
`protobuf` appears to have been introduced 18 months ago via #275 to solve an indirect …
> Remove `protobuf` as a dependency?

- setup.cfg
_For https://github.com/isofit/isofit/issues/418._
Currently the tests operate inside of a Docker container, and `$ conda install isofit`:
https://github.com/isofit/isofit/blob/db3e787560f43519f20d17b6efa3a3865ad23d3e/Dockerfile#L20
prior to `$ pip install`-ing the local version being tested:
https://github.com/isofit/isofit/blob/db3e787560f43519f20d17b6efa3a3865ad23d3e/Dockerfile#L21
The [`conda` package correctly lists `pygrib` as a dependency](https://github.com/conda-forge/isofit-feedstock/blob/1f5811eb96e3150f9d2672cdc4d577e016a8bfc7/recipe/meta.yaml#L28), so I believe that is why the test suite does not currently fail.
> `pygrib` is an unlisted dependency

- isofit/utils/ewt_from_reflectance.py
- isofit/wrappers/ray.py
I see most modules expect to get `ray` from:
```python
from isofit import ray
```
in order to possibly get the local-only wrapper. If this is a project expectation, I think it would be wise to implement something in the test suite that looks for improper imports. Thoughts?
I also removed one unused `import ray`.
> Fix 'ray' imports

- isofit/core/common.py
- isofit/test/test_common.py
Patch to the interpolation function making sure that mlg respects degree/radian based interpolation.
A new test was added to test_common.py to support.
With the additional lines on test_common:
```
fig = plt.figure(figsize=(5,5))
plt.scatter(res_orig.flatten(), res_new.flatten())
plt.xlabel('RG')
plt.ylabel('MLG')
```
We see the following image with the previous interpolation:
With the revision:
Speed tests show minor performance loss (10%), but still an order of magnitude improvement from rg.  Some performance degradation is expected given the dimensionality increase.
@davidraythompson - ready for your review.
> degree interpolation patch

- .readthedocs.yml
- docs/source/requirements.txt
- recipe/environment_isofit_basic.yml
ISOFIT's readthedocs build has been failing since October last year. This PR updates some needed `sphinx` packages and infrastructure to fix the broken build.
@pgbrodrick, could you also resynchronize the webhook for the readthedocs GitHub integration? I appears that I don't have the respective access rights to do that (error message `Webhook activation failed. Make sure you have the necessary permissions`). Background is that previously manually configured webhooks from integrations did not have a secret attached to them. In order to improve security, readthedocs has deployed an update so that all new integrations will be created with a secret, and they're deprecating old integrations without a secret. We must migrate our integrations by January 31, 2024, when they will stop working. In …
> Fix for broken readthedocs build

- .gitignore
- docs/source/custom/CONTRIBUTING.rst
- docs/source/custom/installation.rst
- download-and-build-6s.sh
- download-and-unpack-sRTMnet.sh
- run-tests.sh
- setup-devenv.sh
_For https://github.com/isofit/isofit/issues/418_
Happy to make adjustments as the project maintainers see fit.
This PR adds:
* `.github/workflows/install-python-gdal.sh` - Install the `gdal` Python package. Primarily supports a future change to the CI system, but can also be used during dev environment setup.
* `download-and-build-6s.sh` - Download and build 6s.
* `download-and-unpack-sRTMnet.sh` - Download and unpack sRTM net data.
* `setup-devenv.sh` - A script for setting up a developer environment that _should_ work for most people.
* `run-tests.sh` - Sets appropriate environment variables prior to running tests, and is otherwise a drop-in replacement for `$ pytest`.
It also adds:
* Instructions for how to install `isofit` via `$ pip`.
* Instructions for how to set up a developer …
> Instructions for dev environment setup and a collection of setup scripts

- isofit/utils/downloads.py
- recipe/environment_isofit_basic.yml
- setup.cfg
This PR implements the capability to download extra files that are useful for ISOFIT. This functionality will re-enable support for testing our examples in the new workflows (#421) as well as resolve #393.
- Adds the subcommand `isofit download` which houses other subcommands:
- `data` to download data files from https://github.com/isofit/isofit-data
- `examples` to download from https://github.com/isofit/isofit-tutorials
- Expand commands to include installation of:
> CLI for downloading extras

- docs/source/custom/CONTRIBUTING.rst
- scripts/setup-devenv.sh
I noticed while trying to refresh my development environment that this script may not be working correctly. A virtual environment does not need to be active in order to be modified. This is much simpler than attempting to activate the environment.
> `setup-devenv.sh` improvements

- docs/source/custom/installation.rst
- isofit/__init__.py
- isofit/utils/downloads.py
- recipe/environment_isofit_basic.yml
- setup.cfg
Just a few updates to the new `isofit download` subcommand to include @pl-kevinwurster's suggestions in the comments of #448. 
- Implements Kevin's code to not have to rely on the PyGithub package
- Removed from the install requirements
- Enables `--tag` support to select which release to download
- Added the subcommand to the `isofit` CLI, which was missing in the previous PR
- Updated docs to include a note about this feature
> Downloads CLI updates

- isofit/__main__.py
- isofit/test/test_cli_machinery.py
- isofit/utils/analytical_line.py
- isofit/utils/apply_oe.py
- isofit/utils/empirical_line.py
- isofit/utils/ewt_from_reflectance.py
- isofit/utils/surface_model.py
Small updates to add warnings about old run types.  Also enables click for some utilities (e.g. surface_model) that we didn't support before for convenience.
> Utility click

- .github/workflows/test-pythonpath-ubuntu.yml
Related to https://github.com/isofit/isofit/issues/413
Adds a workflow to the CI ensuring that a `$PYTHONPATH` based install functions correctly. It is possible to run these tests on all versions of Python supported by ISOFIT, however `$PYTHONPATH` is a pretty universal concept, so I think it is sufficient to test on a single version of Python. This also reduces worker contention in the CI system.
> Test '$PYTHONPATH' installation

- .github/workflows/test-pip-package-ubuntu.yml
- .github/workflows/test-pythonpath-ubuntu.yml
- isofit/test/test_cli.py
- isofit/test/test_cli_machinery.py
See inline comments. The `$PYTHONPATH` tests are failing due to the missing `earth_sun_distance.txt` file, which is being handled elsewhere.
> Adjust test paths

- .github/workflows/test-pythonpath-ubuntu.yml
- isofit/test/test_cli_machinery.py
- isofit/utils/atm_interpolation.py
- isofit/utils/empirical_line.py
- isofit/utils/ewt_from_reflectance.py
- isofit/utils/interpolate_atmosphere.py
- recipe/environment_isofit_basic.yml
- setup.cfg
_For https://github.com/isofit/isofit/issues/411_
`matplotlib` is no longer a hard dependency. We discussed this during one of the weekly tagup meetings several months ago, but have not revisited since.
> Remove `matplotlib` as a hard dependency

- isofit/__init__.py
- isofit/core/isofit.py
- isofit/radiative_transfer/luts.py
- isofit/radiative_transfer/radiative_transfer_engine.py
- isofit/utils/analytical_line.py
- isofit/utils/apply_oe.py
- isofit/utils/atm_interpolation.py
- isofit/utils/empirical_line.py
- isofit/utils/ewt_from_reflectance.py
- isofit/utils/extractions.py
- isofit/utils/segment.py
Resolves the OOM errors we were hitting with the ray object store spilling and eventually dying. 
- Moved the shared parameters of `streamSimulation` to ray object space prior to job creation so that they're not duplicated which was exploding the memory
- Fixed ray core dumping at the start of inversions and analytical line by limited `Worker` objects to 1 cpu
- Fixed simulations only utilizing 25% of each core due to the initial guess Isofit object shutting down the ray cluster then re-initializing for the full Isofit run
> Ray Out of Memory

- isofit/configs/sections/radiative_transfer_config.py
- isofit/radiative_transfer/sRTMnet.py
- recipe/environment_isofit_basic.yml
Removes the tensorflow dependency through an numpy implementation of sRTMnet.
Here's a quick validation test (class names don't match exactly due to local implementation).  Formal test can't be run with tf now purged:
```
x = np.random.random([1] + [v for v in model_tf.input_shape if v is not None])
ytf = model_tf.predict(x)
#ynew = apply_model(x, weights, biases)
model = mock_model('/Users/brodrick/isofit_support/sRTMnet_v120.h5')
ynew = model.predict(x)
import matplotlib.pyplot as plt
plt.plot(ytf.squeeze(),c='black', label='Random input raw')
plt.plot(ytf.squeeze() - ynew.squeeze(), label='tf vs np residual')
plt.legend()
```
Needs to wait for zenodo upload to complete, and then this should be ready.
> remove tensorflow

- isofit/__main__.py
- isofit/core/env.py
- isofit/test/test_env.py
- isofit/utils/downloads.py
Attempts to replace the `isofit.root` variable that is used to discover various paths such as tests, data, and examples, with a more flexible `isofit.ini` file that will by default be stored at a user's `~/.isofit/`.
Closes #465
- Implements module `isofit/core/env.py` which houses the functions for managing this "environment" directory
- Uses ConfigParser `ini` files to store path information to persist between runs
- This path can be changed via the CLI in case a user doesn't/can't use the default location
- Expands the `isofit` CLI with override flags to enable setting a value for the run
- Examples:
- `isofit --ini /some/other/path/env.ini apply_oe ...`
- `isofit --data ./data download data` create `./data`, save it in `~/.isofit/isofit.ini` and download the data to it
- `isofit …
> `isofit.root` replacement

- .imgspec/apply_glt.py
- isofit/core/common.py
- isofit/core/isofit.py
- isofit/radiative_transfer/radiative_transfer_engine.py
- isofit/test/test_wray.py
- isofit/utils/analytical_line.py
- isofit/utils/apply_oe.py
- isofit/utils/atm_interpolation.py
- isofit/utils/empirical_line.py
- isofit/utils/ewt_from_reflectance.py
- isofit/utils/extractions.py
- isofit/utils/segment.py
- isofit/wrappers/ray.py
Attempt to cleanup ray initialization to not rely on external calls, now that the procedure has sorted out.  Main changes:
- remove ray_start function that made external ray start calls
- remove ray_shutdown function that made external ray stop calls
- add num_cpu=1 decorators to all ray.remote calls that didn't have them.
This deprecates #472 if accepted.  Removes the error:
```
(raylet) The autoscaler failed with the following error:
Terminated with signal 15
File "/beegfs/store/shared/nostripe/conda-shared-envs/isofit_env/lib/python3.11/site-packages/ray/autoscaler/_private/monitor.py", line 709, in <module>
monitor.run()
File "/beegfs/store/shared/nostripe/conda-shared-envs/isofit_env/lib/python3.11/site-packages/ray/autoscaler/_private/monitor.py", line 584, in run
self._run()
File …
```
> Ray cleanup

- isofit/utils/apply_oe.py
This fixes a bug in assigning the surface elevation LUT grid in case just a mean value is used.
> Patch to surface elevation LUT grid.

- isofit/__init__.py
- isofit/core/common.py
- isofit/radiative_transfer/luts.py
- isofit/radiative_transfer/radiative_transfer_engine.py
I've been running tests in the background for a few architectures to improve the LUT netCDF creation performance. I've tested:
- Mutex: Our current implementation
- Stream: Using a writer queue, simulations return values back to the original ray call to be saved
- Dump: Flushing each point simulation to its own file then merging at the end. This did not scale well when points entered the thousands, so I did not complete tests for this
- Zarr: Not tested too well. This is not a direction the team desires to go so I didn't go far with it, but it still ought to be mentioned as a potential direction to explore
Of these, stream has performed the best. The tests performed measured the overhead incurred by each method by keeping the simulation portion negligible in processing time.
Mutex …
> LUT Creation Improvements

- recipe/environment_isofit_basic.yml
I recognized that ISOFIT's readthedocs build is currently failing since the `sphinx_rtd_theme` was missing in the environment file. I actually fixed [this a few months ago](https://github.com/isofit/isofit/pull/436/files), but it somehow disappeared from the `dev` branch again. As a consequence, our official documentation hasn't been updated to version 3 yet, causing issues like [this](https://github.com/isofit/isofit/issues/466#issuecomment-2050115847).
As soon as this PR is merged, I'll initiate a new version release to get the updated documentation running.
> Fix failing readthedocs build.

- isofit/utils/apply_oe.py
This PR ensures we print the names of the supported sensors when `apply_oe` is called with an unsupported sensor name.
> [Minor] Include names of supported sensors in the "invalid sensor" error message

- isofit/utils/apply_oe.py
In `apply_oe`, EMIT and AVIRIS-3 have custom inversion windows that differ from the default windows, but they are not being used when generating configs. This PR adds the `INVERSION_WINDOWS` variable as an argument when calling `build_main_config` and `build_presolve_config`.
> Added INVERSION_WINDOWS to presolve and main configs

- isofit/core/common.py
- isofit/radiative_transfer/radiative_transfer_engine.py
This PR updates the resampling of a high-resolution prebuilt LUT to the desired instrument spectral response. @pgbrodrick and @jammont, it works now on my end but feel free to test and suggest improvements.
Also, Nimrod's universal LUT contains a few NaNs throughout all simulated quantities, so that the inversion using this table currently crashes (at least, I'm assuming that that's the issue). While we already have a mechanism in play to detect these NaNs in the LUT (throwing a logger warning), we might also need a function that somehow eliminates these values on runtime by replacing them with a reasonable fill value. Open to thoughts here!
> Update resampling of prebuilt LUT.

- isofit/__init__.py
When trying to exit a command line ray processing, the following error started to appear and let the control-c command run in a forever-loop:
> ^CTypeError: shutdown_ray() takes 0 positional arguments but 2 were given
> Exception ignored in: 'ray._raylet.check_signals'
> Traceback (most recent call last):
>   File "/Users/bohn/mambaforge/envs/isofit_env_3x/lib/python3.10/site-packages/ray/_private/worker.py", line 2847, in wait
>     ready_ids, remaining_ids = worker.core_worker.wait(
> TypeError: shutdown_ray() takes 0 positional arguments but 2 were given
To resolve this issue, I removed the custom `shutdown_ray()` function in ISOFIT's `init.py`. Tests confirmed that control-c then works as expected again when exiting ray processes. Also, running a final `ray stop` showed no active …
> Remove custom version of ray shutdown from ISOFIT's init.

- isofit/utils/apply_oe.py
Thanks to Dave Knapp from ASO, we discovered a bug with the new option of building the surface model on runtime. It previously staged just the .json config dict to the working directory, and not the built model. This led the code to fail due to a .mat file value error. This PR fixes the issue.
> Small patch to surface model built on runtime.

- isofit/utils/add_HRRR_profiles_to_modtran_config.py
- recipe/environment_isofit_basic.yml
- setup.cfg
Simply removes `pygrib` from `setup.cfg` and the conda recipe. Adds a warning to the only script that uses it.
> Remove pygrib dependency

- isofit/core/common.py
- isofit/inversion/inverse_simple.py
- isofit/radiative_transfer/radiative_transfer_engine.py
- isofit/surface/surface_lut.py
- isofit/test/test_common.py
- isofit/utils/template_construction.py
Change all LUT interpolation to linear.  This includes removing the angluar components of the RTE, and updating all of the LUT table generation bounds to use a standard linear grid.  This makes everything faster and simpler.  It does continue to permit some inaccuracies for angular dimensions, but if the spacing is tight, this number is small.
> linear interpolation reversion

- isofit/core/common.py
- isofit/radiative_transfer/luts.py
- isofit/radiative_transfer/radiative_transfer_engine.py
This branch re-implements changes that were merged into #505 but are now independent:
- Interpolation improvements in `luts.py`
- Improved the debugging verbosity of `luts.py:load()`
- Resampling of the LUT in `radiative_transfer_engine.py` to be more generalized
- Refactored `common.py:resample_spectrum()` around to be a bit easier to read and tweak. This change has been tested thoroughly as well as has been used operationally in #505. 
- Resolves the NaNs issue by setting values in H to 0
> LUT Interpolation and Resampling

- isofit/core/common.py
- isofit/radiative_transfer/kernel_flows.py
- isofit/radiative_transfer/sRTMnet.py
- isofit/radiative_transfer/six_s.py
This PR adds the calculation of the solar azimuth angle based on given view and relative azimuths to the 6s config module. In addition, it implements a small fix to prevent the solar azimuth angle from taking values larger than 360°, and updates the key mapping in `kernel_flows.py` to respect IPARM 12.
> Update to 6s, sRTMnet, and KF to correctly respect relative azimuth angle.

- isofit/utils/apply_oe.py
There is a log statement that incorrectly reports the mean_to_sun_azimuth with the value of mean_to_sun_zenith.  This caused confusion.  This PR fixes that.
> Fixed log entry where mean_to_sun_azimuth is incorrectly reported

- isofit/radiative_transfer/luts.py
Collection of improvements to the `luts.py` module to increase the loading speed. Present goals are to reduce the loading speed on any LUT to be less than two minutes for any strategy. 
Leaving as a draft while performing ongoing experiments. 
- 🐛 Fixed a bug with subsetting dimensions that are in reversed order. Subsetting wasn't actually working as intended, often leaving the entire dimension in play. As a result, downstream processing could have significant additional overhead, such as interpolation.
> LUT Speedup

- isofit/core/fileio.py
- isofit/core/geometry.py
- isofit/radiative_transfer/engines/modtran.py
- isofit/radiative_transfer/engines/six_s.py
- isofit/test/test_geometry.py
- isofit/utils/analytical_line.py
Moves the loading of the ESD file to the `core/fileio.py:IO` class to maintain consistency with other data loading. Additionally made it an optional parameter to the `Geometry` class. 
This is an alternative implementation to resolve the bug described in #530.
Integrated #527 to fix Black formatting.
> ESD moved to IO

- isofit/core/common.py
We removed nds-k support in commit 79459acf98c8984391e691477607ad7e6bdcc73f but missed removing it as the default style for VectorInterpolator. This fixes that.
Closes #541
> Removed nds-k from VectorInterpolator

- isofit/utils/apply_oe.py
- isofit/utils/template_construction.py
Adds an option to apply_oe which forces all LUT dimensions in the obs/loc files with measurable variation to include at least 2 grid points.  Yet untested in deployments.
Also eliminates redundant get_grid function to prevent confusion.
> Apply oe rt chunk

- isofit/data/build_examples.py
- isofit/data/cli/__init__.py
Discovered some issues while developing #556:
- `image_cube` module wasn't included in the downloads/validate all functions in `isofit.data.cli.__init__`. I updated this by making the discovery of modules automated so that future additions don't need to modify this file
- Image cube examples weren't building due to a missing `configs` directory in the example directory. Updated the build script to auto create this directory if it is needed.
> Examples Build Update

- .github/workflows/docker.yml
- Dockerfile
- docs/Docker-README.md
- docs/source/custom/docker.rst
- docs/source/index.rst
- recipe/environment_isofit_basic.yml
- scripts/startJupyter.sh
This PR finally implements the ability to build our Docker images for multiple architectures using only one Dockerfile.
The command to build the ARM64 and AMD64 images is:
```bash
docker buildx build --platform linux/amd64,linux/arm64 -t jammont/isofit:latest . --push
```
Additionally developed a new github workflow to auto build and push these images on each ISOFIT release. This has been tested and working.
https://hub.docker.com/r/jammont/isofit
> Docker Updates

- isofit/core/fileio.py
- isofit/data/cli/__init__.py
- isofit/data/cli/data.py
- isofit/data/cli/examples.py
- isofit/data/cli/image_cube.py
- isofit/data/cli/sixs.py
- isofit/data/cli/srtmnet.py
- isofit/data/ini.py
- isofit/test/test_cli.py
- isofit/test/test_examples.py
- isofit/utils/template_construction.py
Attempting to provide more helpful debugging/error messages when ISOFIT is missing extra dependencies.
The `validate` functions have added two parameters: `debug` and `error`. These are callables for where to route messages to. By default they route to `print` which is used by the `isofit build` command as there's no logging. However, these change to `logging.debug` and `logging.error` when called from the new `path` function, which is used during an isofit pipeline execution (ie. `apply_oe` or `Isofit().run()`)
This ensures these messages get written to a log file if one exists as well as reduces the verbosity if the logging level is above debug, while maintaining verbosity for the `isofit build` command.
Closes #466
> Helpful Validation

- isofit/utils/ewt_from_reflectance.py
`NotImplementedError` syntax example corrected for EWT command line utility.
> Corrected EWT syntax example

- isofit/radiative_transfer/engines/modtran.py
Runs previously failed for images where the OBSZEN range is smaller than the lut_grid spacing. Modtran.py assumed that there was a lut_grid element for OBSZEN. This adds flexibility to only check for the correct zenith angle convention if the lut key is there.
Alternative to #571 and will close #569.
I'm currently testing that the fix works for a small image on the cluster.
> Added key check on the lut grid for OBSZEN before checking MODTRAN convention

- isofit/data/cli/examples.py
The NEON tutorial needs external data. This PR simply adds a function that will download the external zip and unzip the data to `examples/isotuts/NEON/data`.
The NEON tutorial is in the process of being updated to know where this data will be.
> Download NEON Data

- docs/source/custom/CONTRIBUTING.rst
- docs/source/custom/data.rst
- docs/source/custom/docker.rst
- docs/source/custom/installation.rst
Some docs related to the `data` module weren't displaying correctly. Notable fixes:
- Refactored a table to use proper RST syntax. Was previously not displaying 
- Words wrapped in `` were being indented instead of highlighted, which made sentences awkward to read
- Unfinished dev section describing the templates has now been fleshed out. They weren't supposed to be pushed yet but accidentally got included early, so this cleans them up
- Other sections of the docs now refer to the downloads/data module more consistently
- Removed labradtran from installation docs
- Recommend using `isofit download` for 6s and sRTMnet instead of manually downloading and installing
> Data docs updates

- recipe/environment_isofit_basic.yml
The latest readthedocs build failed because the environment_isofit_basic.yml was missing two packages that were introduced by @jammont's recent updates. This PR adds them.
> Added missing dependencies to environment_isofit_basic.yml to enable successful readthedocs build.

- .github/workflows/docker.yml
- docs/source/custom/data.rst
Fixes the path in the workflow to the docker markdown file as it's now in a different location.
> Docker Markdown Fix

- isofit/utils/template_construction.py
We encountered an edge-case, where rounding in the lut spacing led to the minimum spacing condition being met.  This should only be triggered in the case where we have two grid elements, so rather than modify the rounding (which is convenient), this just adds to that conditional.
> LUT Spacing conditionals

- isofit/utils/apply_oe.py
Both MODTRAN and 6s cannot handle negative sensor altitudes, which are physically implausible anyway. This PR adds a check that raises a `ValueError` in case detected `mean_altitude_km < 0`.
> Sensor altitude check.

- isofit/radiative_transfer/engines/six_s.py
Changes to the engines/six_s.py file to handle 6s outputs that now can provide separated upwards, downwards, direct and diffuse transmittance. 
Note: parse_file function is specific to how we've changed the output files. The outputs are also specific to an edited version of 6s.
Separated 6s transmittance:
Total 6s transmittance from separated values and dev-branch total transmittance:
Comparisons to Modtran:
At low AOD
At high AOD
> Handling multipart transmittances from 6s

- isofit/radiative_transfer/engines/modtran.py
- isofit/radiative_transfer/radiative_transfer_engine.py
This accompanies: https://github.com/pgbrodrick/sRTMnet/pull/1
Two changes here. 
The first is simple. the configure and exit flag was exiting the function before the .json files were being written.
The second is a little bit stranger. I was getting a silent failure when initiating the 6s RT engine initialization (with configure-and_exit). The class call would successfully exit, but not write the files. The added check here will only enter the logging/run status check portion for when the RTE actually runs only if the configure_and_exit flag isn't used.  It seemed to fix the issue.
> Changes to get configure_and_exit flag to work

- isofit/utils/apply_oe.py
- isofit/utils/template_construction.py
While working on the NEON tutorial updates, I saw it fit to clean up the docs of ApplyOE to be a bit more user-friendly as well as make it all available to the CLI. 
Changes:
- Deprecated the use of the dot-notational `args` dict in favour of parameters. This makes it a bit more user-friendly to use the function within a notebook, such as the NEON tutorial
- Updated the docs with missing parameters and fixed a number of typos
- Changed docstring format to Numpy format (style choice, we've been inconsistent and I've implemented this style in other modules such as `data/` and `radiative_transfer`) IMO it's easier to read as it's less a giant block of text
- Added `apply_oe.__doc__` to the `isofit apply_oe` command. This required moving the CLI function to the bottom of the file. This …
> ApplyOE Doc Updates

- isofit/radiative_transfer/engines/sRTMnet.py
- isofit/radiative_transfer/engines/six_s.py
Replacing #619 .  Facilitates new multicomponent RTM.
See this model for testing (prelim only, tuned to EMIT wavelengths, to be updated):
[model](https://popo.jpl.nasa.gov/pub/PBrodrick/isofit/multicomponent_test_20241221.h5)
[aux](https://popo.jpl.nasa.gov/pub/PBrodrick/isofit/multicomponent_test_20241221_aux.npz)
> key fixes to 6s and srtmnet

- .github/workflows/test-pip-package-ubuntu.yml
- .github/workflows/test-pythonpath-ubuntu.yml
The extras cache was working but not in the intended way. On the line `${{ steps.cache-extras.outputs.cache-hit != true }}` the `true` is supposed to be wrapped in quotes. Because it's not, the "cache-hit" never truly hit, so the `Download extras` step would always execute. This generally wasn't an issue because the cache was actually restored so the files are all present, therefore the download command would just skip any products that already exist. As such, no downloading would occur, and the build command is so fast that there really was no impact to the job. 
However, the real issue is that when the cache _doesn't_ exist, the download command would, well, download stuff. Because we use a matrix to test different python versions in parallel, every runner/job would attempt to create …
> Fix workflows cache rate limiting

- isofit/configs/sections/radiative_transfer_config.py
- isofit/core/forward.py
- isofit/core/isofit.py
- isofit/inversion/inverse_simple.py
- isofit/radiative_transfer/engines/sRTMnet.py
- isofit/radiative_transfer/luts.py
- isofit/radiative_transfer/radiative_transfer.py
- isofit/radiative_transfer/radiative_transfer_engine.py
- isofit/surface/surface.py
- isofit/surface/surface_additive_glint.py
- isofit/surface/surface_glint_model.py
- isofit/surface/surface_lut.py
- isofit/surface/surface_multicomp.py
- isofit/surface/surface_thermal.py
- isofit/utils/apply_oe.py
- isofit/utils/template_construction.py
@pgbrodrick @davidraythompson This is a first draft for a simplification of `radiative_transfer.py`. The two main goals are:
1. Clean up transmittance terms, so that, e.g., `transm_down_dif` only holds the diffuse downward transmittance and not the total transmittance (down * up, direct + diffuse), such as in the current sRTMnet and standard MODTRAN case.
2. Integrate different model variations, namely the topography model, the glint model, and adjacency effects into one single radiance model, in particular, remove preclusive if-clauses.
There are two main problems/questions as of now:
1. The proposed new implementation only works if at least one of the variables `transm_up_dir` and `transm_up_dif` is not zero. Otherwise, the term `((E_down_dir + E_down_dif) * (T_up_dir + T_up_dif)) / …
> Clean up and simplification of radiative transfer module

- .github/workflows/test_pip.yml
- pyproject.toml
- recipe/isofit.yml
- Removed `numpy < 2.0` install dependency
- ~~Added Python 3.13 to workflows~~
- Ray still doesn't support it ☹️ 
- Removed version pin on:
- xarray - This was pinned due to a bugged release awhile ago but is now resolved
- netCDF4 - Pinned version didn't work with unpinned numpy
Closes #639
> Relax Dependencies

- isofit/utils/apply_oe.py
Adds a simple `--config_only` flag to apply_oe to exit right before the full run
Closes #646
> Generate config and exit: apply_oe

- isofit/radiative_transfer/radiative_transfer.py
Cases when the spherical albedo term in the lut table are 0 currently produce nan values, which leads exceptions when calculating inverse matrices.
When `s_alb` contains nans, `calc_rdn` returns a vector with partial nans (indexes where `s_alb = 0`). The resample function does not include a check for nans within the `x` vector (only `H`). When `x` contains partial nans, `resample` returns a vector of full nans.
As far as I can tell, this is only an issue with the 1c model. This fix adds a narrow check to the `calc_rdn` function within the 1c if statement for cases when `s_alb = 0`. I tried to make it verbose with a debug log, which could be warning if we want it to always be printed.
With how things are currently structured, the value we replace the nans with does not matter, as the 1c …
> Added check in calc_rdn for s_alb = 0

- isofit/data/build_examples.py
- isofit/data/cli/image_cube.py
- isofit/data/cli/sixs.py
Fixed a few issues with the downloader modules when working with a user to fix their installation:
- `isofit download sixs` was broken due to having the wrong parameters
- Added more context to one of the validation errors
- Disabled piping the error output of the `make` call, hopefully future errors will be outputted rather than quietly being discarded
- Fixed `isofit download imagecube` broken when using a non-default path
- Fixed the example building from templates retrieving non-json files
- MacOS Finder likes to create `.DS_Store` in every directory to casually pollute users' systems which was causing issues with our examples building
The user's issue had to do with their Mac system not having xtools installed correctly. Took a bit of debugging to discover and resolve, so this PR is …
> Downloaders Bugfixes

- isofit/radiative_transfer/luts.py
Attempt to replace #552 with rebase. 
Adds compression to built LUTs. This has minimal runtime impact and massive disk savings for large tables.
> LUT Compression, rebased

- isofit/core/forward.py
- isofit/inversion/inverse_mcmc.py
In #524, `ForwardModel.calc_rdn()` was updated to take `rho_dir_dir` and `rho_dif_dir` instead of a single `rfl` argument:
https://github.com/isofit/isofit/blob/d9a511244782a13a8c0c2c12dda24c8af61c3eb1/isofit/core/forward.py#L189
However, `ForwardModel.calc_meas()` wasn't updated accordingly and still passes a single `rfl` arg to `calc_rdn`:
https://github.com/isofit/isofit/blob/d9a511244782a13a8c0c2c12dda24c8af61c3eb1/isofit/core/forward.py#L215
As a result, any output relying on `calc_meas` -- such as radiometry_correction_file, path_radiance_file, and modeled_radiance_file -- appear to contain incorrect values.
We may want to use named arguments in function calls throughout ISOFIT to make bugs like this impossible.
> Fix incorrect calls to ForwardModel.calc_rdn()

- isofit/__main__.py
- isofit/utils/__init__.py
- isofit/utils/apply_oe.py
- isofit/utils/interpolate_spectra.py
- isofit/utils/template_construction.py
This is motivated by some of the PRISM data, which has a downtrack stripe of NaN values for one of the wavelengths. We were previously running a code block that did the interpolation within `isofit.run`.  This utility would allow us to call the interpolation once, within ApplyOE, and provide an "interpolated input file" that can propagate downstream.
The interpolation uses the same core code block that has been passed around for the PRISM lines:
```python
def interpolate_values(self, meas, replace_nan=False):
if replace_nan:
non_nan_locs = np.argwhere(~np.isnan(meas))
all_replace = np.all(np.isnan(meas))
else:
non_nan_locs = np.argwhere(meas != self.nodata_value)
all_replace = np.all(meas == self.nodata_value)
if all_replace:
return meas, 10
elif len(non_nan_locs) != np.prod(meas.shape): …
```
> Added spectra interpolation function for input RDN files.

- isofit/utils/apply_oe.py
- isofit/utils/interpolate_spectra.py
Managed to slip by my testing. The argument order between the interpolate_spectra function and the apply_oe call was inconsistent.
In the spirit of some other design comments, the inplace flag is now a kwarg.
> Patch to fix interpolate spectra for ApplyOE

- isofit/core/common.py
- isofit/radiative_transfer/radiative_transfer_engine.py
Addresses an issue in #602 where a LUT had the key `surface_elevation` but ISOFIT expects it to be named `surface_elevation_km`. This PR implements a function in `core/common.py` to compare LUT keys with the known geometry keys and if there's an 80% match, output a warning to the user to possibly change it
> Warn if LUT keys are close to known geometry keys

- isofit/utils/apply_oe.py
- isofit/utils/template_construction.py
This PR adds support for AVIRIS-5 data. Unlike AVIRIS-3, it does not include default `INVERSION WINDOWS,` as these can be set in the `apply_oe` call. We may want to consider adding defaults in the future.
Note: There is some code redundancy in `template_construction.py` in the code block that sets the fid. For example, AVIRIS-NG, AVIRIS-3, AVIRIS-5, and PRISM all use the same filename template but have separate conditional statements. A similar issue exists in `apply_oe`.
> Added AVIRIS-5 support

- isofit/utils/apply_oe.py
- isofit/utils/template_construction.py
Presently, the surface_model call from apply_oe will fail if pointing to a directory that doesn't have the wavelength file available (common).  The solution to this is to use the available wavelength_path keyword as a default, which has already been populated by apply_oe.
> Surface_model auto-build patch

- docs/source/custom/data.rst
- docs/source/custom/installation.rst
- isofit/radiative_transfer/engines/six_s.py
- Updated docs for the newer ini path overrides syntax
- Added further clarity to the sixs warning when the `$SIXS_DIR` does not match the loaded INI
Closes #677
> CLI Docs Update

- isofit/__main__.py
- isofit/core/isofit.py
- isofit/data/__init__.py
- isofit/data/download.py
- isofit/data/ini.py
- isofit/utils/template_construction.py
Added new functionality to `ini.py` to convert to/from template configuration files which will make it easier to move a config from one system to another. 
- `toTemplate` converts an existing config file to a template version
- This must be done by the system that created the config to start with as it uses the ini to replace values in strings
- Values found in the ini are replaced with strings `{env.[path]}`, eg. `{env.data}`, `{env.examples}`
- By default, only converts **paths** from the ini, not keys. This is to ensure things like sRTMnet version remains consistent. 
- `template_construction.py` auto does this now for presolve and full, creates the same config but with `.tmpl`
- `fromTemplate` converts a template config back using a different ini. The idea here is:
- A user runs …
> Config Templating

- isofit/radiative_transfer/engines/modtran.py
MODTRAN will write to tp6 log file the theoretical maximum water column vapor and minimum AOT for a given altitude if the user provides one that is out of range for building a LUT. A lot of times this is unavoidable for scenes with wide range of ground altitude. Further, it is non-trivial to implement a rectilinear grid that is based on these theoretical max and mins that are altitude dependent.
Where this impacts ISOFIT the most is during **_Inversion()_** , which uses bounds that were declared during initialization. However, for some altitudes there may not actually be any change in the MODTRAN output, thereby creating a condition where any change in the cost surface (Jacobian) will be virtually nonexistent . This can occur especially for too coarse of water vapor resolution and large …
> MODTRAN polynomials for upper possible bounds of water vapor and lower possible bounds of AOT

- isofit/utils/apply_oe.py
Replaces #703 for clean merge.  From previous:
changes h2o grid lower bound in presolve to 0.2, which is already lower than we ever observe in practice. Below this, many RTMs start to fall apart. The full inversion grid is already bounded, but this bad low end causes some errant retrievals in the presolve.
@unbohn - when checks clear this is ready for review / merge.
> update lower bound

- isofit/utils/apply_oe.py
I forgot to add `av5` to the list of supported sensors in my initial PR for AVIRIS-5 support, this PR fixes that.
> Added 'av5' to list of apply_oe supported sensors

- isofit/radiative_transfer/luts.py
- isofit/radiative_transfer/radiative_transfer_engine.py
- Added a simple `ISOFIT status` attribute to the LUT on creation to track whether it finished being created correctly
- May help debug cases where isofit crashed during lut creation but followup runs attempted to use the prebuilt lut
- Added `Create.getAttr` function to access attributes in the netcdf
- Added RTE dumping the LUT info to debug logs after loading it
- Should help debug external LUTs by having that information always available instead of requesting users to provide it
> LUT Status Attribute

- isofit/inversion/inverse_simple.py
- isofit/utils/surface_model.py
This adds a simple wavelength unit check to `inverse_liquid_water()`. The way the function is set up, wavelengths are required to be in units of nm. Otherwise, EWT results are inaccurate.
> Wavelength unit check for liquid water inversion.

- isofit/configs/sections/radiative_transfer_config.py
When a prebuilt LUT is provided, a number of config checks should just be skipped as they're no longer relevant. 
Closes #757
> Prebuilt LUT bypass config checks
